<?php
    declare(strict_types=1);

    use Magento\Framework\Escaper;
    use Magento\Framework\View\Element\Template;
    use Hyva\SwissupEasytabs\ViewModel\Loader;
    use Hyva\Theme\Model\ViewModelRegistry;

    /** @var Template $block */
    /** @var Escaper $escaper */
    /** @var array $tabs */
    /** @var bool $hasAjaxTabs */
?>

<div class="tab-select-wrapper sm:hidden">
    <label for="tab-select" class="sr-only">Select Tab</label>
    <select 
        class="tab-select border rounded px-4 py-2 w-full"
        @change="activeTab = [parseInt($event.target.value)]<?php if ($hasAjaxTabs): ?>; const [tab] = $event.target.selectedOptions; updateTabContent(tab);<?php endif; ?>"
        role="tablist"
        :aria-activedescendant="activeTab[0] !== undefined ? $root.querySelector('.tab-select').options[activeTab[0]].id : ''"
        aria-label="Tabs"
    >
    <?php $index = 0; foreach ($tabs as $_tab) : ?>
        <?php $alias = $block->escapeHtmlAttr($_tab['alias']); ?>
        <option value="<?= $index ?>" 
            id="tab-label-<?= $alias ?>"
            aria-controls="<?= $alias; ?>"
            role="tab"
            aria-selected="<?= ($index === 0) ? 'true' : 'false' ?>"
            <?php if ($_tab['is_ajax']): ?>data-ajaxurl="<?= $escaper->escapeHtmlAttr($block->getAjaxUrl($alias)) ?>"<?php endif; ?>
            :selected="activeTab.includes(<?= $index ?>)">
            <?= $block->stripTags($_tab['title']) ?>
        </option>
    <?php $index++; endforeach; ?>
    </select>
</div>

<?= $block->fetchView($block->getTemplateFile('layout/collapsed.phtml')); ?>
