<?php
    declare(strict_types=1);

    use Magento\Framework\Escaper;
    use Magento\Framework\View\Element\Template;
    use Hyva\SwissupEasytabs\ViewModel\Loader;
    use Hyva\Theme\Model\ViewModelRegistry;

    /** @var Template $block */
    /** @var Escaper $escaper */
    /** @var ViewModelRegistry $viewModels */
    /** @var array $tabs */

    $loader = $viewModels->require(Loader::class);
?>

<?php foreach ($tabs as $_index => $_tab) : ?>
    <?php
        $alias = $block->escapeHtmlAttr($_tab['alias']);
        $isAjax = $_tab['is_ajax'] ?? false;
    ?>
    <div id="tab-label-<?= $alias ?>"
        class="tab-label flex flex-col items-center pt-6 pb-3 mx-auto mb-4 border-b-2 border-gray-300 md:pt-0 md:block  md:border-0 md:w-1/3 lg:w-1/4"
        <?php if ($_tab['is_ajax']): ?>data-ajaxurl="<?= $escaper->escapeHtmlAttr($block->getAjaxUrl($alias)) ?>"<?php endif; ?>
    >
        <h2 id="tab-label-<?= $alias ?>-title"
            class="text-2xl font-medium text-gray-900 title-font"
        >
            <?= /* @escapeNotVerified */ $_tab['title'] ?>
        </h2>
    </div>
    <div id="<?= $alias; ?>" class="tab-content mb-8 md:w-2/3 lg:w-3/4">
        <?= /* @escapeNotVerified */ $isAjax ? $loader->getHtml() : $_tab['child_html'] ?>
    </div>
<?php endforeach; ?>
