<?php
    declare(strict_types=1);

    use Magento\Framework\Escaper;
    use Hyva\Theme\Model\ViewModelRegistry;
    use Swissup\Easytabs\Block\Tabs;
    use Swissup\HyvaEasytabs\ViewModel\Loader;

    /** @var Tabs $block */
    /** @var Escaper $escaper */
    /** @var ViewModelRegistry $viewModels */
    /** @var array $tabs */

    $loader = $viewModels->require(Loader::class);
?>

<?php $index = 0; foreach ($tabs as $_tab) : ?>
    <?php
        $alias = $escaper->escapeHtmlAttr($_tab['alias']);
        $isAjax = $_tab['is_ajax'] ?? false;
    ?>
    <div id="tab-label-<?= /* @noEscape */ $alias ?>"
        class="tab-label flex flex-col items-center pt-6 pb-3 mx-auto mb-4 md:pt-0<?php if ($block->hasToolbar()) : ?> hidden<? else: ?> border-b-2 border-gray-300 md:block md:border-0 md:w-1/3 lg:w-1/4<?php endif; ?>"
        <?php if ($_tab['is_ajax']): ?>data-ajaxurl="<?= $escaper->escapeHtmlAttr($block->getAjaxUrl($alias)) ?>"<?php endif; ?>
    >
        <h2 id="tab-label-<?= /* @noEscape */ $alias ?>-title"
            class="text-2xl font-medium text-gray-900 title-font"
        >
            <?= $escaper->escapeHtml($_tab['title'], ['span']) ?>
        </h2>
    </div>
    <div id="<?= /* @noEscape */ $alias ?>" class="tab-content mb-8<?php if ($block->hasToolbar()) : ?> w-full<?php else: ?> md:w-2/3 lg:w-3/4<?php endif; ?>">
        <?= /* @noEscape */ $isAjax ? $loader->getHtml() : $_tab['child_html'] ?>
    </div>
<?php $index++; endforeach; ?>
