<?php

declare(strict_types=1);

/** @var \Magento\Framework\Escaper $escaper */
/** @var \Swissup\Easytabs\Block\Tabs $block */

$tabs = $block->prepareTabsData();
if (!$tabs) {
    return;
}

$uniqueId = uniqid();
$htmlId = 'swissup-easytabs-' . $uniqueId;
$tabsLayoutType = $block->getTabsLayoutType();
$isCollapsed = false;
$isExpanded = false;
$isAccordion = false;
$isDefault = false;
switch ($tabsLayoutType) {
    case 'collapsed':
        $isCollapsed = true;
        break;
    case 'expanded':
        $isExpanded = true;
        break;
    case 'accordion':
        $isAccordion = true;
        break;
    default:
        $isDefault = true;
        break;
}

$hasAjaxTabs = in_array(true, array_column($tabs, 'is_ajax'));
$initOptions = json_decode($block->getInitOptions(), true);
if (isset($initOptions['active']) && is_string($initOptions['active'])) {
    $initOptions['active'] = explode(',', $initOptions['active']);
}
?>

<div id="<?= /* @noEscape */ $htmlId ?>" class="product info detailed relative">
    <style>
        #<?= /* @noEscape */ $htmlId ?> #customer-review-list { padding-top: 0; }
        #<?= /* @noEscape */ $htmlId ?> :is(.tab-label, .tabs-toolbar-item) .counter::before { content: '('; }
        #<?= /* @noEscape */ $htmlId ?> :is(.tab-label, .tabs-toolbar-item) .counter::after { content: ')'; }
        #<?= /* @noEscape */ $htmlId ?> section.my-12 { margin-top: 0; margin-bottom: 0; }
        <?php if ($isDefault || $isCollapsed || $block->hasToolbar()): ?>
        #<?= /* @noEscape */ $htmlId ?> .-mb-2px { margin-bottom: -2px; }
        #<?= /* @noEscape */ $htmlId ?> .hover\:border-gray-300:hover { border-color: #D1D5DB; /* Tailwind's gray-300 */ }
        <?php endif; if ($isDefault): ?>
        #<?= /* @noEscape */ $htmlId ?> div[role="tablist"] { display: none; }
        <?= '@media (min-width: 640px) {' ?>
            #<?= /* @noEscape */ $htmlId ?> .sm\:hidden { display: none; }
            <?php if ($isDefault): ?>
            #<?= /* @noEscape */ $htmlId ?> div[role="tablist"] { display: flex; }
            <?php endif; ?>
        <?= '}' ?>
        <?php endif; ?>
    </style>

<?php if ($block->hasToolbar()): ?>
    <?= /* @noEscape */ $block->assign('tabs', $tabs)->fetchView($block->getTemplateFile('tabs-toolbar.phtml')); ?>
<?php endif; ?>

    <div class="product data items <?= $escaper->escapeHtmlAttr($tabsLayoutType) ?><?php if ($isExpanded): ?> md:flex md:flex-wrap<?php endif; ?> w-full mt-8"
        x-data="swissupEasytabs<?= /* @noEscape */ $uniqueId ?>"
        x-defer="intersect"
    >
        <?php if ($isCollapsed): ?>
            <?= /* @noEscape */ $block->assign('tabs', $tabs)->fetchView($block->getTemplateFile('layout/collapsed.phtml')); ?>
        <?php elseif ($isExpanded) : ?>
            <?= /* @noEscape */ $block->assign('tabs', $tabs)->fetchView($block->getTemplateFile('layout/expanded.phtml')); ?>
        <?php elseif ($isAccordion) : ?>
            <?= /* @noEscape */ $block->assign('tabs', $tabs)->assign('initOptions', $initOptions)->fetchView($block->getTemplateFile('layout/accordion.phtml')); ?>
        <?php else : ?>
            <?= /* @noEscape */ $block->assign('tabs', $tabs)->assign('hasAjaxTabs', $hasAjaxTabs)->fetchView($block->getTemplateFile('layout/default.phtml')); ?>
        <?php endif ?>
    </div>
</div>

<?= $block
    ->assign('uniqueId', $uniqueId)
    ->assign('initOptions', $initOptions)
    ->assign('hasAjaxTabs', $hasAjaxTabs)
    ->fetchView($block->getTemplateFile('tabs/script.phtml')); ?>
