<?php
    $tabs = $block->prepareTabsData();
    if (!$tabs) {
        return;
    }

    $uniqueId = uniqid();
    $htmlId = 'swissup-easytabs-' . $uniqueId;
    $tabsLayoutType = $block->getTabsLayoutType();
    $isCollapsed = false;
    $isExpanded = false;
    $isAccordion = false;
    $isDefault = false;
    switch ($tabsLayoutType) {
        case 'collapsed':
            $isCollapsed = true;
            break;
        case 'expanded':
            $isExpanded = true;
            break;
        case 'accordion':
            $isAccordion = true;
            break;
        default:
            $isDefault = true;
            break;
    }

    $hasAjaxTabs = false;
    foreach ($tabs as $_tab) {
        if (!empty($_tab['is_ajax'])) {
            $hasAjaxTabs = true;
            break;
        }
    }
?>

<div class="product info detailed">
    <style>
        #<?= $htmlId ?> #customer-review-list > :first-child { display: none; }
        #<?= $htmlId ?> .tab-label .counter::before { content: '('; }
        #<?= $htmlId ?> .tab-label .counter::after { content: ')'; }
        #<?= $htmlId ?> section.my-12 { margin-top: 0; margin-bottom: 0; }<?php if ($isDefault): ?>
        #<?= $htmlId ?> .-mb-2px { margin-bottom: -2px; }
        #<?= $htmlId ?> .hover\:border-gray-300:hover { border-color: #D1D5DB; /* Tailwind's gray-300 */ }
        <?= '@media (min-width: 640px) {' ?>
            #<?= $htmlId ?> .sm\:hidden { display: none; }
        <?= '}' ?><?php endif; ?>
    </style>
    <div id="<?= $htmlId ?>"
        class="product data items <?= $tabsLayoutType ?> w-full mt-8"
        x-data="swissupEasytabs<?= $uniqueId ?>"
        x-defer="intersect"
    >
        <?php if ($isCollapsed): ?>
            <?= $block->assign('tabs', $tabs)->fetchView($block->getTemplateFile('layout/collapsed.phtml')); ?>
        <?php elseif ($isExpanded) : ?>
            <?= $block->assign('tabs', $tabs)->fetchView($block->getTemplateFile('layout/expanded.phtml')); ?>
        <?php elseif ($isAccordion) : ?>
            <?= $block->assign('tabs', $tabs)->fetchView($block->getTemplateFile('layout/accordion.phtml')); ?>
        <?php else : ?>
            <?= $block->assign('tabs', $tabs)->assign('hasAjaxTabs', $hasAjaxTabs)->fetchView($block->getTemplateFile('layout/default.phtml')); ?>
        <?php endif ?>
    </div>
</div>

<script>
    document.addEventListener('alpine:init', () => {
        Alpine.data('swissupEasytabs<?= $uniqueId ?>', () => ({
            activeTab: 1,
            getActivePanel() {
                return this.$root.querySelectorAll('[role=tabpanel]')[this.activeTab-1];
            }<?php if ($hasAjaxTabs) :?>,
            isLoading: false,
            fetchTabContent(url) {
                return fetch(url, {
                    method: 'GET',
                    headers: {
                        'Content-Type': 'application/json',
                        'X-Requested-With': 'XMLHttpRequest'
                    }
                }).then(response => response.text());
            },
            processScripts(html) {
                const tempDiv = document.createElement('div');
                tempDiv.innerHTML = html;
                const scripts = tempDiv.querySelectorAll('script:not([type="text/x-magento-init"]');
                scripts.forEach(script => {
                    if (script.type && script.type !== 'text/javascript') return;
                    const newScript = document.createElement('script');
                    newScript.textContent = script.textContent;
                    document.body.appendChild(newScript);
                    script.remove();
                });

                return tempDiv.innerHTML;
            },
            async updateTabContent(tab) {
                const { ajaxurl } = tab.dataset;
                if (!ajaxurl || this.isLoading) return;
                this.isLoading = true;
                const panel = this.getActivePanel();
                const content = await this.fetchTabContent(ajaxurl);
                const processedContent = this.processScripts(content);
                panel.innerHTML = processedContent;
                delete tab.dataset.ajaxurl;
                this.isLoading = false;
            }<?php endif; ?>
        }));
    });
</script>
