<?php declare(strict_types=1);

use Magento\Framework\Escaper;
use Swissup\Easytabs\Block\Tabs;

/** @var Tabs $block */
/** @var Escaper $escaper */
/** @var array $tabs */

$firstAlias = $escaper->escapeHtmlAttr($tabs[0]['alias']);
$collideObject = implode(', ', array_map(
    fn($tab) => "'" . $escaper->escapeHtmlAttr($tab['alias']) . "': false",
    $tabs
));
?>

<script src="<?= $escaper->escapeUrl($block->getViewFileUrl('Swissup_HyvaEasytabs::js/tabs-toolbar.js')) ?>" defer></script>

<div class="tabs-toolbar sticky top-0 z-10 flex bg-container"
    x-data="hyvaTabsToolbar({ <?= /* @noEscape */ $collideObject ?> }, '<?= /* @noEscape */ $firstAlias ?>')">
    <?php foreach ($tabs as $tab):
        $alias = $escaper->escapeHtmlAttr($tab['alias']); ?>
        <a href="#<?= /* @noEscape */ $alias ?>"
            class="tabs-toolbar-item flex-1 text-center py-2 px-4 font-semibold border-b-2 truncate focus:outline-none transition-all duration-200"
            :class="isActive('<?= /* @noEscape */ $alias ?>') 
               ? 'active border-primary text-primary'
               : 'text-gray-400 border-transparent hover:border-gray-300'"
            @click.prevent="scrollToPanel('<?= /* @noEscape */ $alias ?>')"
            @scroll.window="checkCollision('<?= /* @noEscape */ $alias ?>')">
            <?= $escaper->escapeHtml($tab['title'], ['span']) ?>
        </a>
    <?php endforeach; ?>
</div>