<?php
    $tabs = $block->prepareTabsData();
    if (!$tabs) {
        return;
    }

    $htmlId = uniqid('swissup-easytabs-');
    $tabsLayoutType = $block->getTabsLayoutType();
    $isCollapsed = false;
    $isExpanded = false;
    $isAccordion = false;
    $isDefault = false;
    switch ($tabsLayoutType) {
        case 'collapsed':
            $isCollapsed = true;
            break;
        case 'expanded':
            $isExpanded = true;
            break;
        case 'accordion':
            $isAccordion = true;
            break;
        default:
            $isDefault = true;
            break;
    }
?>

<div class="product info detailed">
    <style>
        #<?= $htmlId ?> #customer-review-list > :first-child { display: none; }
        #<?= $htmlId ?> .tab-label .counter::before { content: '('; }
        #<?= $htmlId ?> .tab-label .counter::after { content: ')'; }
        #<?= $htmlId ?> section.my-12 { margin-top: 0; margin-bottom: 0; }<?php if ($isDefault): ?>
        #<?= $htmlId ?> .-mb-2px { margin-bottom: -2px; }
        #<?= $htmlId ?> .hover\:border-gray-300:hover { border-color: #D1D5DB; /* Tailwind's gray-300 */ }
        @media (min-width: 640px) {
            #<?= $htmlId ?> .sm\:hidden { display: none; }
        }<?php endif; ?>
    </style>
    <div id="<?= $htmlId ?>"
        class="product data items <?= $tabsLayoutType ?> w-full mt-8"
        x-data="{ activeTab: 1 }"
    >
        <?php if ($isCollapsed): ?>
            <?= $block->assign('tabs', $tabs)->fetchView($block->getTemplateFile('layout/collapsed.phtml')); ?>
        <?php elseif ($isExpanded) : ?>
            <?= $block->assign('tabs', $tabs)->fetchView($block->getTemplateFile('layout/expanded.phtml')); ?>
        <?php elseif ($isAccordion) : ?>
            <?= $block->assign('tabs', $tabs)->fetchView($block->getTemplateFile('layout/accordion.phtml')); ?>
        <?php else : ?>
            <?= $block->assign('tabs', $tabs)->fetchView($block->getTemplateFile('layout/default.phtml')); ?>
        <?php endif ?>
    </div>
</div>
